spring:
  datasource:
    url: jdbc:mysql://localhost:3306/securitydb?useSSL=false&serverTimezone=UTC
    username: admin
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    properties:
      hibernate.hbm2ddl.auto: create-drop
      hibernate.format_sql: true

server:
  port: 8081

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/

info:
  environment: predeterminado
